# Stage 1: build
FROM node:22-alpine as builder

WORKDIR /app
COPY ./src/client ./
RUN npm install && npm run build

# Stage 2: serve
FROM nginx:alpine
COPY --from=builder /app/dist /home/BetSolver/src/client/dist

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
